        ;;                      A simple switch program
        ;;
        ;;                      everything after a ";" is a comment                                                 Memory location

        list    p=12f675        ; tells the assembler exactly which PIC chip we are using                               .....
                                ;                                                                                       .....
        org     0x000           ; the microprocessor always starts here after a reset                                   .....
        goto    Program_start   ; jump to the start of the program in memory location 0x005                             0x000
                                ;                                                                                       .....
        org     0x005           ; Tells the compiler to put the next instruction in location 0x005                      .....
                                ; this is because the first five locations 0x000-0x004 are special                      .....
                                ;                                                                                       .....
Program_start                   ; gives the label "Program_start" to the next location to be used                       .....
                                ;                                                                                       .....
        bsf     0x03, 5         ; set the fifth bit of the register at location 3 (select register bank 1)              0x005
        movwf   0x10            ;                                                                                       0x006
                                ;                                                                                       .....
        ;; the next two instructions set all IO pins as inputs to start with (high impedence) except the two we plan to use for LED 0
        movlw   B'00001111'     ; load the working register W with this bit pattern                                     0x007
        movwf   0x05            ; store W in location 5 (of bank 1) - the tristate IO register                          0x008
                                ;                                                                                       .....
        movlw   B'10000000'     ; store this bit pattern in the OPTION REGISTER                                         0x009
        movwf   0x01            ; this disables the internal weak pull-ups on inputs                                    0x00A
                                ;                                                                                       .....
        bcf     0x03, 5         ; select register bank 0                                                                0x00B
        clrf    0x05            ; clear the output register                                                             0x00C
                                ;                                                                                       .....
Main_loop                       ;                                                                                       .....
        clrwdt                  ; clear the watchdog timer - this tells the chip that the program is running OK         0x00D
                                ;                                                                                       .....
        btfss   0x05, 3         ; test bit 3 of the general purpose IO register (this is connected to the switch)       0x00E
        goto    Led_on          ;  and skip this instruction if the bit is set so if it's clear we jump to Led_on       0x00F
                                ;                                                                                       .....
        clrf    0x05            ; turn the LED off                                                                      0x010
        goto    Main_loop       ; and return to the beginning of the main loop                                          0x011
                                ;                                                                                       .....
Led_on                          ;                                                                                       .....
        movlw   B'00000100'     ; store this bit pattern in the general purpose io register                             0x012
        movwf   0x05            ; this sets output 4 high and output 5 low which turns LED 0 on                         0x013
        goto    Main_loop       ; and go round the main loop again                                                      0x014
                                ;                                                                                       .....
        end                     ; says our program is complete                                                          .....